using System.Collections;

public class HitMasks
{
	public static BitArray GetIgnoreMask(int unit_or_shot)
	{
		BitArray bitArray = new BitArray(84);
		switch (unit_or_shot)
		{
		case 15:
			bitArray[17] = true;
			bitArray[20] = true;
			bitArray[28] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[18] = true;
			bitArray[24] = true;
			bitArray[23] = true;
			bitArray[27] = true;
			bitArray[6] = true;
			bitArray[21] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[39] = true;
			bitArray[26] = true;
			return bitArray;
		case 50:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 48:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 46:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 83:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 79:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 6:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 17:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 49:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 76:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 65:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 60:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 26:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 66:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 40:
			bitArray[17] = true;
			bitArray[20] = true;
			bitArray[28] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[18] = true;
			bitArray[24] = true;
			bitArray[23] = true;
			bitArray[27] = true;
			bitArray[6] = true;
			bitArray[21] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[39] = true;
			bitArray[26] = true;
			return bitArray;
		case 8:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 9:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 3:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 67:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 70:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 54:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 47:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 21:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 73:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 41:
			bitArray[17] = true;
			bitArray[20] = true;
			bitArray[28] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[18] = true;
			bitArray[24] = true;
			bitArray[23] = true;
			bitArray[27] = true;
			bitArray[6] = true;
			bitArray[21] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[39] = true;
			bitArray[26] = true;
			return bitArray;
		case 78:
			bitArray[54] = true;
			bitArray[61] = true;
			bitArray[17] = true;
			bitArray[65] = true;
			bitArray[48] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[46] = true;
			bitArray[44] = true;
			bitArray[55] = true;
			bitArray[70] = true;
			bitArray[53] = true;
			bitArray[56] = true;
			bitArray[52] = true;
			bitArray[58] = true;
			bitArray[63] = true;
			bitArray[47] = true;
			bitArray[45] = true;
			bitArray[6] = true;
			bitArray[59] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[67] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[60] = true;
			bitArray[4] = true;
			bitArray[69] = true;
			bitArray[49] = true;
			bitArray[62] = true;
			bitArray[57] = true;
			bitArray[15] = true;
			bitArray[50] = true;
			bitArray[51] = true;
			bitArray[64] = true;
			bitArray[39] = true;
			bitArray[66] = true;
			return bitArray;
		case 77:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 58:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 69:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 45:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 44:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 23:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 22:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 4:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 25:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 19:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 53:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 51:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 81:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 5:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 59:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 18:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 82:
			bitArray[17] = true;
			bitArray[20] = true;
			bitArray[28] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[18] = true;
			bitArray[24] = true;
			bitArray[23] = true;
			bitArray[27] = true;
			bitArray[6] = true;
			bitArray[21] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[39] = true;
			bitArray[26] = true;
			return bitArray;
		case 74:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 63:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 52:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 61:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 57:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 55:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 80:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 24:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 39:
			bitArray[17] = true;
			bitArray[20] = true;
			bitArray[28] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[18] = true;
			bitArray[24] = true;
			bitArray[23] = true;
			bitArray[27] = true;
			bitArray[6] = true;
			bitArray[21] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[39] = true;
			bitArray[26] = true;
			return bitArray;
		case 30:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[17] = true;
			bitArray[41] = true;
			bitArray[30] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[40] = true;
			return bitArray;
		case 28:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 68:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 27:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 62:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[9] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[26] = true;
			bitArray[27] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[18] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 20:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[62] = true;
			bitArray[4] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[8] = true;
			bitArray[5] = true;
			return bitArray;
		case 75:
			bitArray[15] = true;
			bitArray[22] = true;
			bitArray[26] = true;
			bitArray[17] = true;
			bitArray[19] = true;
			bitArray[41] = true;
			bitArray[20] = true;
			bitArray[30] = true;
			bitArray[18] = true;
			bitArray[27] = true;
			bitArray[4] = true;
			bitArray[25] = true;
			bitArray[6] = true;
			bitArray[3] = true;
			bitArray[28] = true;
			bitArray[21] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			bitArray[40] = true;
			bitArray[23] = true;
			return bitArray;
		case 64:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		case 56:
			bitArray[15] = true;
			bitArray[9] = true;
			bitArray[41] = true;
			bitArray[40] = true;
			bitArray[6] = true;
			bitArray[8] = true;
			bitArray[25] = true;
			bitArray[39] = true;
			bitArray[5] = true;
			bitArray[24] = true;
			return bitArray;
		default:
			return bitArray;
		}
	}

	public static float[] GetHitModifier(int unit_or_shot)
	{
		float[] array = new float[84];
		switch (unit_or_shot)
		{
		case 15:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 50:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 48:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 46:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 83:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 79:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 6:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 17:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 49:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 76:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 65:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 60:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 26:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 66:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 40:
			array[15] = 1f;
			array[5] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			return array;
		case 8:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 9:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 3:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 67:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 70:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 54:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 47:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 21:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 73:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 41:
			array[15] = 1f;
			array[5] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			return array;
		case 78:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 77:
			array[15] = 1f;
			array[5] = 1f;
			return array;
		case 58:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 69:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 45:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 44:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 23:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 22:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 4:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 25:
			array[15] = 1f;
			array[5] = 1f;
			array[49] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			return array;
		case 19:
			array[15] = 1f;
			array[5] = 1f;
			array[49] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			return array;
		case 53:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 51:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 81:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 5:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 59:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 18:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 82:
			array[15] = 1f;
			array[5] = 1f;
			return array;
		case 74:
			array[15] = 1f;
			array[5] = 1f;
			return array;
		case 63:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 52:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 61:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 57:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 55:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 80:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 24:
			array[15] = 1f;
			array[5] = 1f;
			array[49] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			return array;
		case 39:
			array[15] = 1f;
			array[5] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			return array;
		case 30:
			array[15] = 1f;
			array[9] = 1f;
			array[17] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			array[6] = 1f;
			array[3] = 1f;
			array[8] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[40] = 1f;
			return array;
		case 28:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 68:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 27:
			array[15] = 1f;
			array[5] = 1f;
			array[44] = 0.8f;
			array[4] = 1f;
			array[3] = 1f;
			array[49] = 1f;
			array[62] = 1f;
			return array;
		case 62:
			array[15] = 1f;
			array[22] = 1f;
			array[9] = 1f;
			array[19] = 1f;
			array[41] = 1f;
			array[20] = 1f;
			array[30] = 1f;
			array[26] = 1f;
			array[27] = 1f;
			array[25] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[28] = 1f;
			array[21] = 1f;
			array[18] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			array[23] = 1f;
			return array;
		case 20:
			array[15] = 1f;
			array[5] = 1f;
			array[49] = 1f;
			array[3] = 1f;
			array[4] = 1f;
			array[62] = 1f;
			return array;
		case 75:
			array[15] = 1f;
			array[46] = 0.7f;
			array[5] = 1f;
			array[44] = -1f;
			array[45] = 0.7f;
			return array;
		case 64:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		case 56:
			array[15] = 1f;
			array[9] = 1f;
			array[41] = 1f;
			array[30] = 1f;
			array[6] = 1f;
			array[8] = 1f;
			array[25] = 1f;
			array[39] = 1f;
			array[5] = 1f;
			array[24] = 1f;
			array[40] = 1f;
			return array;
		default:
			return array;
		}
	}
}
